# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ui(object):
    def setupUi(self, ui):
        ui.setObjectName("ui")
        ui.setWindowModality(QtCore.Qt.ApplicationModal)
        ui.resize(700, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ui.sizePolicy().hasHeightForWidth())
        ui.setSizePolicy(sizePolicy)
        ui.setMinimumSize(QtCore.QSize(700, 480))
        ui.setMaximumSize(QtCore.QSize(700, 480))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        ui.setFont(font)
        self.btn_convert = QtWidgets.QPushButton(ui)
        self.btn_convert.setGeometry(QtCore.QRect(220, 400, 171, 61))
        self.btn_convert.setObjectName("btn_convert")
        self.invert_f = QtWidgets.QCheckBox(ui)
        self.invert_f.setGeometry(QtCore.QRect(390, 220, 181, 40))
        self.invert_f.setObjectName("invert_f")
        self.x_size = QtWidgets.QDoubleSpinBox(ui)
        self.x_size.setGeometry(QtCore.QRect(220, 120, 100, 45))
        self.x_size.setMinimum(1.0)
        self.x_size.setMaximum(999.99)
        self.x_size.setProperty("value", 88.0)
        self.x_size.setObjectName("x_size")
        self.label_2 = QtWidgets.QLabel(ui)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 191, 40))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ui)
        self.label_3.setGeometry(QtCore.QRect(30, 220, 181, 40))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ui)
        self.label_4.setGeometry(QtCore.QRect(30, 320, 131, 40))
        self.label_4.setObjectName("label_4")
        self.y_size = QtWidgets.QDoubleSpinBox(ui)
        self.y_size.setGeometry(QtCore.QRect(220, 220, 100, 45))
        self.y_size.setMinimum(1.0)
        self.y_size.setMaximum(999.99)
        self.y_size.setProperty("value", 88.0)
        self.y_size.setObjectName("y_size")
        self.width = QtWidgets.QSpinBox(ui)
        self.width.setGeometry(QtCore.QRect(220, 320, 100, 45))
        self.width.setMinimum(1)
        self.width.setProperty("value", 5)
        self.width.setObjectName("width")
        self.l_layer = QtWidgets.QLabel(ui)
        self.l_layer.setGeometry(QtCore.QRect(390, 120, 81, 40))
        self.l_layer.setObjectName("l_layer")
        self.threshold = QtWidgets.QSpinBox(ui)
        self.threshold.setGeometry(QtCore.QRect(560, 320, 100, 45))
        self.threshold.setMaximum(255)
        self.threshold.setProperty("value", 125)
        self.threshold.setObjectName("threshold")
        self.label_6 = QtWidgets.QLabel(ui)
        self.label_6.setGeometry(QtCore.QRect(390, 320, 151, 40))
        self.label_6.setObjectName("label_6")
        self.layer = QtWidgets.QComboBox(ui)
        self.layer.setGeometry(QtCore.QRect(480, 120, 191, 40))
        self.layer.setMaxVisibleItems(11)
        self.layer.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.layer.setObjectName("layer")
        self.layer.addItem("")
        self.layer.addItem("")
        self.layer.addItem("")
        self.layer.addItem("")
        self.layer.addItem("")
        self.layer.addItem("")
        self.layer.addItem("")
        self.layer.addItem("")
        self.layer.addItem("")
        self.layer.addItem("")
        self.btn_getfile = QtWidgets.QToolButton(ui)
        self.btn_getfile.setGeometry(QtCore.QRect(551, 40, 121, 40))
        self.btn_getfile.setObjectName("btn_getfile")
        self.label = QtWidgets.QLabel(ui)
        self.label.setGeometry(QtCore.QRect(30, 40, 121, 40))
        self.label.setObjectName("label")
        self.sourcefullpath = QtWidgets.QLineEdit(ui)
        self.sourcefullpath.setGeometry(QtCore.QRect(150, 40, 391, 40))
        self.sourcefullpath.setObjectName("sourcefullpath")

        self.retranslateUi(ui)
        self.layer.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(ui)

    def retranslateUi(self, ui):
        _translate = QtCore.QCoreApplication.translate
        ui.setWindowTitle(_translate("ui", "图片转LCEDA封装库生成器"))
        self.btn_convert.setText(_translate("ui", "生成图片"))
        self.invert_f.setText(_translate("ui", "图像取反"))
        self.label_2.setText(_translate("ui", "X最大尺寸/mm"))
        self.label_3.setText(_translate("ui", "Y最大尺寸/mm"))
        self.label_4.setText(_translate("ui", "线宽/mil"))
        self.l_layer.setText(_translate("ui", "层级"))
        self.label_6.setText(_translate("ui", "图像阈值"))
        self.layer.setCurrentText(_translate("ui", "顶层阻焊层"))
        self.layer.setItemText(0, _translate("ui", "顶层"))
        self.layer.setItemText(1, _translate("ui", "底层"))
        self.layer.setItemText(2, _translate("ui", "顶层丝印层"))
        self.layer.setItemText(3, _translate("ui", "底层丝印层"))
        self.layer.setItemText(4, _translate("ui", "顶层焊盘层"))
        self.layer.setItemText(5, _translate("ui", "底层焊盘层"))
        self.layer.setItemText(6, _translate("ui", "顶层阻焊层"))
        self.layer.setItemText(7, _translate("ui", "底层阻焊层"))
        self.layer.setItemText(8, _translate("ui", "边框层"))
        self.layer.setItemText(9, _translate("ui", "文档层"))
        self.btn_getfile.setText(_translate("ui", "选取文件"))
        self.label.setText(_translate("ui", "图片路径"))
        self.sourcefullpath.setText(_translate("ui", "/home/kearney/Documents/Lan/PIC2LCEDA/ddl.bmp"))

